### ISSUE TITLE
Still unable to build...

### ISSUE THREAD

**Issue by jdukat** [cppan/tesseract_example#1]
Hey FYI - I've been reporting problems with building tesseract on windows (using cppan). With your sample, I have exactly the same problem.
Earlier on, I tried getting binary dll's, generating lib files from them and linking with my code. But i get heap corruption after trying to recognize some simple text. Some people on internet report similar issues but haven't found a clue on how to solve it. Looks like I won't be able to use tesseract on windows unless I am able to build it myself. Is there any option to build tesseract libs without using cppan?

**Comment by egorpugin** [comment]
Hi,

There's old good way of downloading leptonica, its deps, building them all manually, setting up paths and building tess. Personally, I hate this way and because of this I developed cppan.
Also you can try this way https://github.com/tesseract-ocr/tesseract/wiki/Compiling#30401
Didn't test that myself.

But I'm very very interested in cppan working on any system, so if you have some time to spend on this issue I'd like to suggest us to chat somewhere (maybe in skype) and you'll show me screen demonstration or give remote control, so I can track the issue and fix it. Or atleast we'll know what's the issue is on your system.

**Comment by jdukat** [comment]
I believe this is root cause of all the evil problems:

-- Build files have been written to: C:/Users/jarek/.cppan/storage/obj/03/76/d289/build/amd64-msvc-19.0-32
CMake Error at C:/Users/jarek/.cppan/storage/obj/03/76/d289/generate.cmake:106 (include):
include could not find load file:

C:/Users/jarek/.cppan/storage/obj/03/76/d289/build/amd64-msvc-19.0-32/exports/pvt_cppan_demo_gif__5_1_4-fixed.cmake

Note the -fixed suffix. These files do not exist anywhere in cppan storage folder tree.
We can schedule a remote debug session today afternoon (i'm in CET time zone), say at 5 or 6pm I should have enough free time.

**Comment by egorpugin** [comment]
Looks good to me. Feel free to ping me at skype `egor.pugin` when you're ready near that time.

**Comment by jdukat** [comment]
ok, will do. meanwhile, i'll try some more debug...

**Comment by egorpugin** [comment]
Uh-oh. Do you have cppan in PATH???
I just though that the issue can be caused with unavailability cppan program in PATH.
So, if you're executing cppan executable near the sources and it's not in path, the build won't work.

**Comment by jdukat** [comment]
Omg, this may have been the problem. Build in progress... i no longer see those errors mentioned above.

**Comment by jdukat** [comment]
Ok, now better, but still without ultimate success.
The solution for tesseract has been created, compilation fails at linking:

7>LINK : fatal error LNK1104: cannot open file 'C:\Users\jarek.cppan\storage\lib\amd64-msvc-19.0-32\Debug\pvt.cppan.demo.leptonica-master.lib'

Folder C:\Users\jarek.cppan\storage\lib is empty.

**Comment by jdukat** [comment]
Well, this is becoming really frustrating :(

Above mentioned error was when trying to build tesseract solution.
I have tried the example from this repo also, with_cppan, also with errors. Attached console log.
[cmd.zip](https://github.com/cppan/tesseract_example/files/465367/cmd.zip)

**Comment by egorpugin** [comment]
Did you try to remove cppan storage again?
Probably there could be some bad effects from previous incorrect builds.
Does it work with clean building?

---

I'll add an error message when cppan is not in PATH.

**Comment by jdukat** [comment]
Tried that, same result. Looks like inside cppan storage the source libs are not compiled at all.

I've found this though:
https://github.com/peirick/VS2015_Tesseract

Funny thing. I've found this when started preparations to build leptonica and other dependencies from scratch. Worked out of the box and now my app which uses tesseract also works. Please consider adding it to tesseract build instructions (as an alternative to cppan).

**Comment by egorpugin** [comment]
I wrote this in the comment: https://github.com/cppan/tesseract_example/issues/1#issuecomment-246102449 :)
Link from that commit https://github.com/tesseract-ocr/tesseract/wiki/Compiling#30401 will lead you to wiki and the to that github repository.

**Comment by jdukat** [comment]
Hah, lol... I wanted to have the latest greatest lib, and the solution was just one line below :)
And it worked with latest sources, too.

**Comment by egorpugin** [comment]
So, would you still like to debug your issues?

**Comment by jdukat** [comment]
oh, ok, let's do that

**Comment by jdukat** [comment]
Resolved with cppan update. Thanks Egor!!!
