### ISSUE TITLE
Force static linkage of the `with_cmake` project with specific dependency versions (using VS 2015)

### ISSUE THREAD

**Issue by vidiecan** [cppan/tesseract_example#2]
At first, thanks for cppan!

Hopefully, these will be questions rather than issues.

1. I have tried several cppan configurations but to no avail.
The expected result of building with_cmake is one statically linked executable and not an executable with a  bunch of dlls. What shall I add to cppan.yml? I would be thankful if you could also show how to update CMakeLists.txt (if necessary)?

2. Is there a way to force cppan to use specific dependency versions of other dependencies instead of the ones used by cppan? E.g., I want to specify a different libpng version or at least keep it stable.

**Comment by egorpugin** [comment]
1. cppan.yml
```
local_settings:
  use_shared_libs: false 
  #build_shared_libs: false # or this form
```

For cmake:
```
set(CPPAN_BUILD_SHARED_LIBS 0)
add_subdirectory(.cppan) 
```

2. Not (yet?) implemented. I'll think about it, but no guarantees.

**Comment by egorpugin** [comment]
As a temporary solution for `2.` you can "fork" all libraries that use png (many of them, including tesseract) on cppan, and build them. This is very subtle area in dependency management at all.

**Comment by vidiecan** [comment]
1. works, closing.
