### ISSUE TITLE
Problem compiling on Windows

### ISSUE THREAD

**Issue by vacovnik** [cppan/tesseract_example#3]
Hi!
I've been trying to compile OpenCV 3.2 with Tesseract 4.0 on Windows 10 for two weeks now and I've almost gave up.

Now I tried to compile this example to see if elementary things works and even this returns 871 errors.
Can you please help me with that issue?
Thanks in advance!

**Comment by egorpugin** [comment]
Hi, sure.
What are you trying to accomplish?
I need more info on your setup or project needs.
Personally, I tried simple opencv+tess bunch and it worked fine.

**Comment by vacovnik** [comment]
I'm mostly Linux user and got it all up and running on Ubuntu in no time.
The problem is, that I have to work on Windows, because modules I'm going to program will be later used in LabVIEW on a Windows device.
I then tried to build Tesseract using cppan, but got tons of errors: char followed by bool... and a lot of various warnings.
When I run cppan in Tesseract directory, it also does not find a lot of includes, which I think is the main reason for failure.
Am I maybe missing something critical on my machine?

**Comment by egorpugin** [comment]
Do you use cmake in your project?
I mean there's `opencv.text` package already on cppan site, so when you build it, it does everything for you including tesseract 4.0. And with cmake it's easy to include it into your project.
https://cppan.org/pvt.cppan.demo.intel.opencv.contrib.text/version/3.2.0

You could try to run `cppan --build pvt.cppan.demo.intel.opencv.contrib.text-3.2.0`. 

Also I know about one bug in cppan that might be stopping you from correct building. I'm working on it, so if the command above not working (as well as tess build), probably it is the bug.

Feel free to add me in skype (egor.pugin) to work on your issue faster. Maybe I can give you some experimental builds of cppan client with bugs fixed just to check if your issue is gone.

**Comment by vacovnik** [comment]
Thank you! I'll add you in Skype.

**Comment by Pleiades0428** [comment]
Hi, egorpugin. I'm trying to compile tesseract with VS2012(v110) using cppan. I created a cppan.yml 
`local_settings:`
`build:`
`generator: Visual Studio 11 2012`
`toolset: v110`
But I got 17115 error.
Does cppan support tesseract with VS2012?
Looking forward to your reply.

**Comment by egorpugin** [comment]
Hi! Tesseract can be compiled with cppan on VS2015 and higher as I remember.

**Comment by Pleiades0428** [comment]
Oh, thank you very much.
But I wonder is there any way I can build tesseract with VS2012?
The lastest tesseract windows installer seems do not contain dev libs & dlls any more.
I got stuck here.

**Comment by egorpugin** [comment]
The latest tess requires vs2015+. It's in readme.
So, you can only do manual fixing observed errors and compiling for you.

**Comment by TheHippiez** [comment]
I'm not sure if this is the right place... I've been trying to compile Tesseract for VS15. I kinda just want to use Tesseract with openCV in the same project, however building Tesseract on windows is starting to get really frustrating. I've tried a lot of different things so far, but with cppan I did the following:

Install cppan,
install cmake,
run the instructions giving by Cppan.

However, I do can't figure out how to proceed from there. What dependencies do I add? What to include? I'm out of ideas at the moment.

**Comment by egorpugin** [comment]
Check out this tesseract + opencv demo: https://github.com/cppan/webcam_demo

**Comment by TheHippiez** [comment]
I stumbled across that, however it unfortunately doesn't help me.  Visual studio will not recognize
#include <tesseract/baseapi.h>
#include <leptonica/allheaders.h>

Pulled and installed everything
Build everything
Added dependencies 
**C++General**C:\opencv330\build\include;tesseract.lib;openjpeg.lib;libwebp.lib;libtiff.lib;libtesseract.lib;libpng.lib;liblept.lib;libjpeg.lib;jbig2enc.lib;giflib.lib;zlib.lib;%(AdditionalIncludeDirectories)
**Linker General** tesseract.lib;openjpeg.lib;libwebp.lib;libtiff.lib;libtesseract.lib;libpng.lib;liblept.lib;libjpeg.lib;jbig2enc.lib;giflib.lib;zlib.lib;C:\opencv330\build\x64\vc14\lib
**Linker input** opencv_world330d.lib;tesseract.lib;openjpeg.lib;libwebp.lib;libtiff.lib;libtesseract.lib;libpng.lib;liblept.lib;libjpeg.lib;jbig2enc.lib;giflib.lib;zlib.lib;%(AdditionalDependencies)

Am I missing something?

**Comment by egorpugin** [comment]
It's very hard to add everything to VS manually. Such actions were not really intended.
Probably you should open a solution that generated near cpp file. But still it does not help with integration into your own solution.

**Comment by TheHippiez** [comment]
You seem to have combined both openCV and tesseract into one project. Do you have a detailed step-by-step of this proces? There must be some minor thing I'm missing.

**Comment by egorpugin** [comment]
You should create `cppan.yml` config file with contents as in https://github.com/cppan/webcam_demo/blob/master/webcam_demo.cpp#L2
```
dependencies:
    - pvt.cppan.demo.intel.opencv.contrib.text: 3
    - pvt.cppan.demo.intel.opencv.highgui: 3
    - pvt.cppan.demo.intel.opencv.features2d: 3
    - pvt.cppan.demo.intel.opencv.videoio: 3
```
Then add your project files and try to build with `cppan --build .` or simply generate solution with `cppan --generate .`
Opencv's contrib.text package already has a link to tesseract.
https://cppan.org/pvt.cppan.demo.intel.opencv.contrib.text/version/3.2.0

**Comment by TheHippiez** [comment]
Is there a more in depth explanation of how the .yml file helps with these sort of things? Because I have no idea how this works or how I can use that file for my project. I know the github documentation for it exists, I read through it, but as a "newbie" to this part of development it doesn't really explain anything...

**Comment by TheHippiez** [comment]
@egorpugin The dependencies you listed is everything from openCV? At this point I have no clue what to do. I take the cppan.yml I have, add the dependencies. But how does this work with visual studio? Do I just put my cpp's and hpp's in the same folder?

**Comment by vacovnik** [comment]
Hi!
I had the same problem a while ago and I solved it just by frst compiling leptonica and than tesseract using cppan and visual studio.
Afterwards I just used cmake gui for getting things ready for compiling opencv.
I don't recall exactly, what are the cmake flags for defining tesseract and leptonica paths, but you can find them using cmake gui and set them correctly. 
Then copy all needed tesseract .h files in folder tesseract and point to that folder.
It should compile just fine.

**Comment by TheHippiez** [comment]
Thats something I'm going to try! I might get back to you with some
questions based on this, I'm so bad at these things. Trying to get better
:)

**Comment by TheHippiez** [comment]
@vacovnik Do you have a step-by-step super newb for this proces? I  don't quite know the required commands in cppan/ cmake to make it work.

**Comment by vacovnik** [comment]
I don't quite remember all the steps, I just know that I compiled leptonica and tesseract separately using cppan and copied allheader files from folders api, ccmain, ccstruct and ccutil in folder tesseract somewhere and then set cmake variables Tesseract_INCLUDE_DIR to point to parent directory of that tesseract folder including header files, Tesseract_LIBRARY pointing to tesseract*.lib and Lept_LIBRARY to leptonica*.dll
For everithing else I just followed instructions on opencv site: https://docs.opencv.org/3.2.0/d3/d52/tutorial_windows_install.html
