### ISSUE TITLE
cl.exe 0xc000007b in windows 10

### ISSUE THREAD

**Issue by happiness-2025** [cppan/tesseract_example#4]
Hi tesseract community members, 

I follow Tesseract Example as picture as below.
![image](https://cloud.githubusercontent.com/assets/22110501/25768292/6f16f350-3234-11e7-86b8-9d929e4e3d90.png)

I face cl.exe 0xc000007b problem when I type cmake ..  
![image](https://cloud.githubusercontent.com/assets/22110501/25768318/c4e8fd64-3234-11e7-8778-c158d01122a2.png)

My command line error result as below.
![image](https://cloud.githubusercontent.com/assets/22110501/25768336/fece9854-3234-11e7-9674-b67b8a7a3d9e.png)

CMakeError.log as below
[CMakeError.txt](https://github.com/cppan/tesseract_example/files/980583/CMakeError.txt)

Can anybody tell me how can I solve this problem? thanks!

**Comment by egorpugin** [comment]
Simple question - do you have a compiler?

**Comment by happiness-2025** [comment]
Hi,

Thanks for your reply, I'm really need help, my compiler is QT 5.9 for
android, mingw.

Egor Pugin <notifications@github.com>於 2017年5月6日 週六，16:14寫道：

**Comment by egorpugin** [comment]
It's a bad statement. You have to 1) install visual studio 2017 or 2) google how to pass mingw compiler to cmake.

**Comment by happiness-2025** [comment]
Hi,

I have installed the vs2017, but the error message still appear, how can I
do? Thanks.

Regards,

Egor Pugin <notifications@github.com>於 2017年5月6日 週六，16:30寫道：

**Comment by egorpugin** [comment]
Install the latest cmake from https://cmake.org. During installation check Add to PATH option.
(Check your cmake version `cmake --version`, it must be at least 3.8.0, previous versions does not work with new visual studio.)

**Comment by happiness-2025** [comment]
The error message still appear, do I need to use VS 2017 to compile or just use the instruction as below?
![image](https://cloud.githubusercontent.com/assets/22110501/25807234/a96f53fc-3438-11e7-8618-6c990363f974.png)

my cmake version as below,
![image](https://cloud.githubusercontent.com/assets/22110501/25807067/26d5604e-3438-11e7-821f-bd431ea90b58.png)

my PATH option list as below,
![image](https://cloud.githubusercontent.com/assets/22110501/25807467/81fcb188-3439-11e7-9331-78ea21f04cde.png)

Need help, thanks.
Regards,

**Comment by egorpugin** [comment]
What is your OS version?

**Comment by happiness-2025** [comment]
Windows 10

**Comment by egorpugin** [comment]
Again... what error do you see? And for what application?

**Comment by happiness-2025** [comment]
cl.exe, 0xc000007b, my visual studio 2017 is enterprise edition.
![image](https://cloud.githubusercontent.com/assets/22110501/25828688/36f95060-3484-11e7-8822-14342a628710.png)
![image](https://cloud.githubusercontent.com/assets/22110501/25828753/8d47a2d2-3484-11e7-8df6-48bd693efce3.png)
![image](https://cloud.githubusercontent.com/assets/22110501/25828759/96996ac8-3484-11e7-96bd-9aca243c51da.png)
CMakeError.log as below,
[CMakeError.txt](https://github.com/cppan/tesseract_example/files/985054/CMakeError.txt)

**Comment by egorpugin** [comment]
I see you also have Visual Studio 2013? Maybe you need to remove it?
Also the error is from cl.exe, so ask microsoft about that.

**Comment by happiness-2025** [comment]
Is this project only suitable for VS 2013?

**Comment by egorpugin** [comment]
No, it works for vs2015,vs2017.

**Comment by happiness-2025** [comment]
Hi egorpugin,

I uninstall all my visual studio old component and reinstall vs 2017 in my computer, but I get the new error message as below.
![image](https://cloud.githubusercontent.com/assets/22110501/26243552/db702d66-3cbe-11e7-99b9-2ee2013837c8.png)

I totally have no idea what's going on, can you tell me why? thanks.
Regards,

**Comment by egorpugin** [comment]
You must find how to correctly invoke cmake in your environment. Google it. Seems, it's not related to cppan.
Personally, I don't see this before, so you need to look around.
