### ISSUE TITLE
Failed to compile on Windows 10 with with_cppan

### ISSUE THREAD

**Issue by datengx** [cppan/tesseract_example#5]
C:\Users\xxxx\.cppan\storage\src\38\cb\0305\src\ccmain\equationdetect.cpp(235): error C3688: invalid literal suffix '锟?; literal operator or literal operator template 'operator ""锟? not found [C:\Users\Da\.cppan\storage\obj\38\cb\0305\build\d58c02e4\cppan\38cb0305\38cb0305.vcxproj] [C:\Users\Da\.cppan\storage\obj\b0\93\c5a8\build\d58c02e4\b093c5a8-b-d.vcxproj

Shows many errors like this.

**Comment by egorpugin** [comment]
See https://github.com/cppan/cppan/issues/54
